### ISSUE TITLE
Move container image from wongma7 namespace to kubernetes

### ISSUE THREAD

**Issue by rothgar** [kubernetes-incubator/nfs-provisioner#34]
The container as an official kubernetes incubator should be either in the docker hub's kuberenete's user namespace or in gcr.io under the kubernetes namespace.

I know it seems kinda dumb but if/when ops or management audit containers being used and see wongma7/nfs-provisioner vs kuberenetes/nfs-provisioner there will be more questions around who's wongma7.

Would be better if the provisioner at least appeared more official

**Comment by wongma7** [comment]
Sure, will find out how to do that

**Comment by wongma7** [comment]
Thanks, the image is now hosted at `quay.io/kubernetes_incubator/nfs-provisioner:v1.0.0` and I'm updating all the docs and yamls. https://github.com/kubernetes-incubator/nfs-provisioner/pull/35 . 

(Side-note, will also change references to my name which are all over the place to something more sensible :))

**Comment by rothgar** [comment]
Thanks for the fast turn around! Much easier to get approvals and makes the docs more official looking.
