### ISSUE TITLE
file permissions in pod

### ISSUE THREAD

**Issue by jianhuiz** [kubernetes-incubator/nfs-provisioner#39]
I was trying to deploy this kubernetes galera sample
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/testing-manifests/petset/mysql-galera/petset.yaml
However the mysql pod failed due to change the ownership to mysql:mysql of path /var/lib/mysql which is a nfs volume
```
ubuntu@k8s2m:~$ kubectl logs mysql-0
+ tempSqlFile=/tmp/mysql-first-time.sql
+ '[' '!' -d /var/lib/mysql/mysql ']'
@a
+ echo @a
+ set -- mysqld --defaults-file=/etc/mysql/my-galera.cnf --user=root
+ chown -R mysql:mysql /var/lib/mysql
chown: changing ownership of '/var/lib/mysql/ibdata1': Operation not permitted
chown: changing ownership of '/var/lib/mysql/ib_logfile1': Operation not permitted
chown: changing ownership of '/var/lib/mysql/test': Operation not permitted
...
```
I found that the owner of the files create in the nfs volume was 4294967294 which I suppose related to the nfs root squash. I wonder is there an way solving this?
```
/srv/pvc-6c4e5982-c7c2-11e6-bed8-fa163ed5b15b/mysql:
total 110600
drwx------ 5 4294967294 4294967294      110 Dec 21 21:15 .
drwxrwxrwx 3 root       root             19 Dec 21 21:15 ..
-rw-rw---- 1 4294967294 4294967294 12582912 Dec 21 21:15 ibdata1
-rw-rw---- 1 4294967294 4294967294 50331648 Dec 21 21:15 ib_logfile0
-rw-rw---- 1 4294967294 4294967294 50331648 Dec 21 21:15 ib_logfile1
drwx------ 2 4294967294 4294967294     4096 Dec 21 21:15 mysql
drwx------ 2 4294967294 4294967294     4096 Dec 21 21:15 performance_schema
drwx------ 2 4294967294 4294967294        6 Dec 21 21:15 test

```

**Comment by wongma7** [comment]
You're right, root squash mode is not configurable atm. I'll fix it tonight and push v1.0.1, this is not the only app that expects to chown things.

**Comment by jianhuiz** [comment]
Cool, looking forward to v1.0.1.
Thanks

**Comment by wongma7** [comment]
@jianhuiz I pushed it, it should just work once you bump your provisioner to v1.0.1 because the default behavior is now to *not* root_squash all exports. I tested it using the same mysql example but please confirm :)

**Comment by jianhuiz** [comment]
works like a charm 👍
