### ISSUE TITLE
nfs-provisioner in container outside of k8s hostname issues

### ISSUE THREAD

**Issue by dohnto** [kubernetes-incubator/nfs-provisioner#76]
Hello, 

I must run nfs-provisioner outside of kubernetes cluster and I would like to run it as a container.

I run the container using `docker ... --net=host ...` in order to let propagate the real hostname of the machine. I run it on my machine with hostname `machine.test` (debian jessie)

The problem is [this line](https://github.com/kubernetes-incubator/nfs-provisioner/blob/d05c82d3f540f74c078ddce17d7b0952be0bdfa0/pkg/volume/provision.go#L288), when `hostname -i` is called. My `/etc/hosts` is following:
```
127.0.0.1 localhost
127.0.1.1 machine.test
```

The `hostname -i` in such case returns `127.0.1.1`, which is propagated to kubernetes/etcd and no PVs cannot be created.

As a dirty hack  I use my own implementation of `hostname` which I mount to `/usr/local/sbin` and which returns the public IP of `machine.test` (output of `host machine.test`)

**Comment by wongma7** [comment]
I see, it just arbitrarily picks the first output of `hostname -i` at the moment. I'm not sure how to make that smarter so I will implement a way for you to set the hostname yourself when you do `docker run`. Probably via an environment variable or a flag.
