### ISSUE TITLE
[Question] External NFS server

### ISSUE THREAD

**Issue by sdurrheimer** [kubernetes-incubator/nfs-provisioner#85]
Hi,

Quick question, does it work with a external NFS server ?

Thanks in advance,

**Comment by wongma7** [comment]
if by external NFS server you mean something where you can edit /etc/exports, then yes it can add & remove entries to /etc/exports if you run it as root, but it isn't well tested: https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/docs/deployment.md#outside-of-kubernetes---binary (the repo has been renamed to "external-storage")

**Comment by sdurrheimer** [comment]
By external, I mean, the NFS server that I might be using is not managed by me or kubernetes but I would like to use it as a dynamic provisioner for my volumeClaims.

If I understand correctly, the nfs-provisioner runs a ganesha NFS server, but can be disabled but I was not sure how to refer to my external NFS server.

**Comment by wongma7** [comment]
Ok I see, well nfs-provisioner can only handle the case where it's running *on* the host on which the external nfs server is running: like if you tell it your host is running Ganesha it will do dbus things to create shares, else it will edit /etc/exports and run "exportfs" for you. It isn't aware of any APIs for talking to external nfs servers or anything like that, it had to be running on the same host as the server 

Maybe check out Netapp trident?

**Comment by wongma7** [comment]
@sdurrheimer after reading https://github.com/kubernetes-incubator/external-storage/issues/5 I think I misunderstood what you're looking for, sorry. Is what he describes what you mean? Basically: a provisioner that mounts an external NFS directory, creates directories in it, and then creates PVs for those directories. This is pretty much what https://github.com/wongma7/efs-provisioner does

**Comment by wongma7** [comment]
@sdurrheimer so this is certainly possible but let's move discussion over to  kubernetes-incubator/external-storage#5 . still need to decide if it should be a feature of nfs-provisioner or a new program entirely.

**Comment by sdurrheimer** [comment]
ok sounds good.
